### ISSUE TITLE
Include default logging configuration

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#197]
Currently, it's entirely up to the user to configure their logging implementation of choice. #196 will add more information on how to do that.

In general, it would be helpful for users to have logs for troubleshooting. We could include a `logging.properties` file that logs to a `.briefcase.log` file:

```
handlers=java.util.logging.FileHandler

.level=INFO

java.util.logging.FileHandler.pattern=.briefcase.log
java.util.logging.FileHandler.limit=50000
java.util.logging.FileHandler.count=1
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS.%1$tL %4$-7s %3$s %5$s: %6$s%n
```

It looks like other projects such as [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html) provide default configurations. 

Is this a good idea? Is this the right default file? It logs up to 50kb in one file and then starts over in that file. I figure logging at level `INFO` makes sense since the log levels used are currently a bit arbitrary.

@yanokwa @dcbriccetti @batkinson @daveycrockett

**Comment by daveycrockett** [comment]
Yup, I see this as almost a must-have for any desktop app. Way easier to help users with issues when you can have them send you stack traces.

**Comment by batkinson** [comment]
> Currently, it's entirely up to the user to configure their logging implementation of choice

Yeah, I think "user" in this context is a little misleading. That may have been my fault based on my description. The selection of the logging provider should be made at the time of bundling everything up as an application. So that "user" would be the briefcase developers. The facades allow the library developers to defer that choice to the application developers, rather than forcing them to use logging framework X just because the library chose to use that.

After resurfacing and taking a look at the current state of briefcase, I think it makes sense to:

- Add the slf4j-simple binding to the project, which will remove the warning and restore functionality
- Exclude commons-logging and use jcl-over-slf4j instead so JCL logging is unified by routing into slfj4

I fixed this rather quickly locally and will submit a PR so you can see what I did. Despite being called "simple" the slf4j simple binding is probably overkill for briefcase's usage.

-

**Comment by lognaturel** [comment]
#204 is no doubt a big improvement and thank you for that, @batkinson! I still don't quite understand the bridging between slf4j and jcl and why adding the analytics dependency specifically caused problems. Is it because it explicitly added the `jcl-over-slf4j` dependency? It didn't occur to me that other libs would use slf4j since none of those had previously caused problems but of course they do.

How do we do logging moving forward in Briefcase? Do we keep using JCL calls in new classes for consistency? Use SLF4J in new classes and eventually move everything over?

I meant this issue to cover specifying a logging implementation a default configuration that would log to a file that might help troubleshoot user problems. The simple slf4j binding logs to Stderr which most users won't see. @batkinson are you saying you think logging to a file is overkill?

**Comment by batkinson** [comment]
> I still don't quite understand the bridging between slf4j and jcl and why adding the analytics dependency specifically caused problems. Is it because it explicitly added the jcl-over-slf4j dependency?

So, the problem was that the library bundled a dependency on slf4j-api (which is very common for libraries):
```sh
~/briefcase $ ./gradlew dependencies
...
+--- com.brsanthu:google-analytics-java:1.1.2
|    +--- org.slf4j:slf4j-api:1.7.5
|    +--- org.slf4j:jcl-over-slf4j:1.7.5
|    |    \--- org.slf4j:slf4j-api:1.7.5
```
As soon as that happened, briefcase needed to specify an slf4j binding. Oddly, this library also bundled jcl-over-slf4j which is not a binding for slf4j, but a logging bridge that *replaces* the commons-logging library with a binary compatible api which routes logging through slf4j instead. Normally, this isn't supplied by libraries, since they can't know what you'll choose for the final logging implementation. If you include *both* commons-logging and the bridge, the first one on the classpath wins and you get unpredictable behavior. If slf4j's JCL bridge won, you wouldn't see the messages because there was no binding. If commons-logging won, it depends on what commons-logging resolves to for its ultimate logging implementation.

> I meant this issue to cover specifying a logging implementation AND a default configuration

This was my mistake. I did not mean to include the close in the commit message. I  just meant to contribute this as a fix so it was possible for logging to be used at all (making this possible).

> @batkinson are you saying you think logging to a file is overkill?

No I was just saying this should be, hopefully, a straight forward logging configuration. You just need to [configure the simple logger using the available properties](https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html). I could be wrong since briefcase currently is a little unconventional in how it uses logging (CLI/GUI with CLI using it as its primary feedback). If so, then you just need to change out the simple-binding for whatever you think should work better. FWIW, given how briefcase works currently, I would prioritize making briefcase work more conventionally than getting exotic with logging config.

Here's an example you could use in a simplelogger.properties file:

```
# Log to a file at INFO
org.slf4j.simpleLogger.logFile=.briefcase.log
org.slf4j.simpleLogger.defaultLogLevel=info
```

You could also squelch some of the log levels if they're too noisy, but it's probably better to rectify the levels in code unless they are from a 3rd party.

Lastly, as I noted on https://github.com/opendatakit/briefcase/pull/204#issuecomment-331947952 you can tweak levels when you run the command:

```
# Start briecase with http components debug logging enabled
java -Dorg.slf4j.simpleLogger.log.org.apache.http=debug -Dorg.slf4j.simpleLogger.log.org.apache.http.wire=error -jar "build/libs/ODK Briefcase v1.8.0.-extra-stuff.jar"
```

**Comment by lognaturel** [comment]
Thank you, @batkinson!! You are the best. ✨
